
networks: 
  dev:

services: 
  nginx:
    image: nginx:stable-alpine
    ports:
      - "81:81"
    volumes: 
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on: 
      - database
      - front
    networks: 
      - dev
  database:
    build:
      context: ./database
    volumes: 
      - .:/usr/app
      - /usr/app/node_modules
    networks: 
      - dev
  front:
    build:
      context: ./front
    networks: 
      - dev